version: '3.7'
#
services:
  irissvc:
    build:
      context: ./build
      args:
        COMMIT_ID: adbkdemo
    image: wolfman0719/adbk:demo
    container_name: adbkdemo
    init: true
    hostname: myiris
    
    ports:
    # superserver default port 
    - "51782:51773"
    # webserver/management portal port
    - "52782:52773"
    
    environment:
    - TZ=JST-9