version: '3.7'
#
services:
  irissvc:
    build:
      context: .
      args:
        COMMIT_ID: adbkdemo
    image: wolfman0719/adbk:demo
    container_name: adbkdemo
    init: true
    hostname: myiris
    command: --check-caps false
    ports:
    # superserver default port 
    - "51773:1972"
    # webserver/management portal port
    - "52773:52773"
    
    environment:
    - TZ=JST-9
