zn "%SYS"

Do ##class(Security.Users).UnExpireUserPasswords("*")
Do ##class(Config.NLS.Locales).Install("jpuw")
set sec = ##class("Security.Applications").%%New()
set sec.Name = "/api/adbk"
set sec.NameSpace = "USER"
set sec.DispatchClass ="ADBK.Broker"
set sec.AutheEnabled = 32
set status = sec.%%Save()

zn "USER"
set io = ##class(%SYS.NLS.Device).SetIO("UTF8")
Do $system.OBJ.ImportDir("/intersystems/iris/adbk/",,"ck",,1)
halt
